### Buscar todo os ID 
GET http://localhost:3333/user/

### Buscar ID especifico 
GET http://localhost:3333/user/2e794ad6-c8c6-4527-8bab-41a407ba6632

### Inserir Informação no banco 
POST http://localhost:3333/user/ 
content-type: application/json

{
"name": "MILTODELA", "avatar": "MILTO@DELA.com", "telefone": "XXX"
}

### Deletar um usuario pelo ID no banco 
DELETE http://localhost:3333/user/1f6d5045-882c-48bf-9b82-312a69b7230e
### Atualizar um usuario pelo ID no Banco 
PUT http://localhost:3333/user/f6795f1f-a941-4378-ab23-407e827bdbc0
content-type: application/json

{
"name": "Juninho Arrasta", "avatar":"XXX", "telefone": "111"
}

