### Buscar todo os ID
GET http://localhost:3333/user/

### Buscar ID especifico
GET http://localhost:3333/user/02d29b7f-146e-41b6-ae67-dcc82f902ff2

### Inserir Informação no banco
POST http://localhost:3333/user/
content-type: application/json

{
    "name": "FEMA 1",
    "avatar": "fema@fema.com",
    "numero": "XXX"
}

### Deletar um usuario pelo ID no banco
DELETE  http://localhost:3333/user/33792419-f948-43bb-be91-b4d90f9c18f9
### Atualizar um usuario pelo ID no Banco
PUT  http://localhost:3333/user/356d4072-9f7e-4c5b-a336-b5e02a8c36f8
content-type: application/json

{
    "name": "Juninho Arasta",
    "avatar":"XXX",
    "numero": "111"
}

